# playbook.yml
- name: Deploy monitoring stack
  hosts: all
  become: yes
  vars_files:
    - vars/global.yml

  roles:
    - node_exporter
    - alertmanager
    - grafana
    - prometheus
    - process_exporter
    - blackbox_exporter
    - mimir
    - pushgateway
    - nginx_prometheus_exporter
    - nginx
    - postgres_exporter
    - postgresql
